### ISSUE TITLE
Nesting / Pagination parameters not working 1.0.6

### ISSUE THREAD

**Issue by breebee** [akeeba/engage#74]
### Steps to reproduce the issue
-Upgrade to 1.0.6
1. Set number of comments per page to 5
2. Set nesting to 1
3. Use default cassiopeia template / no overrides

### Expected result

1 nested indentation with pagination after every 5 comments

### Actual result

Paramaters not considered, pagination breaks

### Troubleshooting already performed

Resolves when reverting back to 1.0.0b2

When upgrading the same error as 1.0.5 last reported occurs

Warning
JInstaller: :Install: File does not exist /var/www/mms/tmp/install_6023cc0f61b05/engage-1.0.6/component/backend/vendor
Component Update: Failed to copy administrator files.
Error
Error installing component

Joomla 4 beta 8 - dev
Php 8.0 fpm
nginx/1.14.0
10.1.47-MariaDB-0ubuntu0.18.04.1
Ubuntu Linux 4.15.0-135-generic

**Comment by nikosdion** [comment]
It does work, see my own site e.g. https://www.dionysopoulos.me/making-a-portable-full-installation-of-ubuntu-on-a-usb-hdd.html#akengage-comments-section I have set up a limit of 20 comments and nesting 3 levels deep.

The way it works is that all comments are loaded and their nesting is taken into account, creating a tree. Then we skip `akengage_limitstart` nodes (any level) from the top of the tree and display "limit" number of nodes. The pagination is performed by changing the `akengage_limitstart` in the URL.

This is the observable behaviour in my live site and all of my development sites. 

If you observe a different behaviour I need you to explicitly define what "pagination breaks" is supposed to mean and the exact full URLs you see in the first and second page of paginated comments.

**Comment by breebee** [comment]
The behavior when adding ?akengage_limitstart=5 triggers the nesting, cuts 12 comments to 7 instead of 5, and fails to generate the pagination. I think there may simply be an issue with the packages, while downgrading to 1.0.0.b2 does resolve the issue it also gives a warning about a newer FOF or other library used, and while upgrading to 1.0.6 the other above error mentioned is given. I will run a fresh install of 1.0.6 to confirm the case is single to my condition later today.

**Comment by nikosdion** [comment]
I still don't understand what "cuts 12 comments to 7 instead of 5" and "fails to generate the pagination" means. I have tried reproducing your issue but it's really hard when I'm basically shooting in the dark.

Can you please provide me a dump of your `#__engage_comments` table with the body, name, email, ip columns blanked out? Also tell me what is the asset ID of the article you are trying to display comments on. Further to that, please show me screenshots of the entire comments area for the first page and the second page of comments. Without this information I have no idea what you mean or how to try and reproduce this issue.

**Comment by nikosdion** [comment]
OK, I figured out what you were trying to say. Selecting a comments limit that's different than the site's default list limit didn't work. Instead, the default list limit was used (by default it's 20).

You probably have 12 comments, therefore you see all of them in one page (12 < 20). Changing the URL parameter to skip the first 5 comments does work, as you said, and displays 7 comments which is normal: it skips the first 5 comments, 7 are remaining, 7 < 20 so all 7 remaining comments are shown.

I have fixed that for the next release, 2.0.0, scheduled for release in **March**, on or around March 6th.

**Comment by breebee** [comment]
Unfortunately I have removed the installation prior to your comment, however I noticed when removing the extensions the version of engage was at 1.0.4 rather then 1.0.6. Installing with a clean 1.0.6 package I am still receiving the following

JInstaller: :Install: File does not exist /var/www/mms/tmp/install_6023d7fbc96d3/engage-1.0.6/component/backend/vendor
Component Install: Failed to copy administrator files.
Error
Error installing component

I removed all engage files folders and database tables, including all of akeeba backup. Are you able to install the 1.0.6 package on a clean instance?

**Comment by breebee** [comment]
Installing from https://www.akeeba.com/download/official/engage/1-0-6/pkg_engage-1-0-6-zip.zip rather then github works! Thanks

**Comment by nikosdion** [comment]
The GitHub ZIP package is not an installable extension. It's an archive of the repository. The build instructions are in the README — or, like it's recommended for most users, you just go to https://www.akeeba.com/downloads.html and download the prebuilt, versioned, installation ZIP package :)
